[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "text2splatter"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["text2splatter"]